//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaDanhMucSach
    {
        public int IDDanhMuc { get; set; }
        public int IDSach { get; set; }
        public string TenTacGia { get; set; }
        public string NhaXuatBan { get; set; }
        public string NamXuatBan { get; set; }
        public string TheLoai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
