//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap_SanPham
    {
        public int IDNhaCungCap { get; set; }
        public int IDSanPham { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
