//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class KinhNghiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KinhNghiem()
        {
            this.NhanVien_KinhNghiem = new HashSet<NhanVien_KinhNghiem>();
        }
    
        public int ID { get; set; }
        public string CongViec { get; set; }
        public string DiaDiem { get; set; }
        public string BangCap { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien_KinhNghiem> NhanVien_KinhNghiem { get; set; }
    }
}
